version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: hackathon-postgres
    environment:
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: hackathon_password
      POSTGRES_DB: hackathon_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - hackathon-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: hackathon-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - hackathon-net

  fastapi:
    build:
      context: ./backend  # Path to your FastAPI app directory
    container_name: fastapi_app
    environment:
      - DB_HOST=db
      - DB_USER=hackathon_user
      - DB_PASSWORD=hackathon_password
      - DB_NAME=hackathon_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Map the backend directory into the container
    depends_on:
      - db
    networks:
      - hackathon-net
    command: uvicorn server.app:app --host 0.0.0.0 --port 8000 --reload

networks:
  hackathon-net:
    driver: bridge
